language: node_js

node_js:
  - 8 # Latest 8.x series LTS
  - 10 # Latest 10.x series LTS
  - 12 # Latest 10.x series LTS
  - 14 # Latest 10.x series LTS
  - node # Latest released to date

before_install:
  - npm i -g npm --upgrade

script:
  - npm test
  - npm run lint
